name: urban_market
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  image_picker: ^1.0.4
  http: ^1.1.0
  logger: ^2.0.2+1
  collection: ^1.17.2
  cloud_functions: ^4.7.4
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/