// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupicvaRYmXfUkfugF74_Rai0VmyrhoOY',
    appId: '1:598593524647:web:e712b831a316a2577e1c82',
    messagingSenderId: '598593524647',
    projectId: 'urban-market-c3d86',
    authDomain: 'urban-market-c3d86.firebaseapp.com',
    storageBucket: 'urban-market-c3d86.firebasestorage.app',
    measurementId: 'G-P0C4HZYSZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7xQHjRyK21SvrnhN2Nm1NPF8tbm85fk',
    appId: '1:598593524647:android:ea8336493ccbb8a07e1c82',
    messagingSenderId: '598593524647',
    projectId: 'urban-market-c3d86',
    storageBucket: 'urban-market-c3d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmHUsMfLDfVxLOvZnqhGseOBKBf5ZZkU',
    appId: '1:598593524647:ios:6a158c37a8e71cdd7e1c82',
    messagingSenderId: '598593524647',
    projectId: 'urban-market-c3d86',
    storageBucket: 'urban-market-c3d86.firebasestorage.app',
    iosBundleId: 'com.example.urbanMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmHUsMfLDfVxLOvZnqhGseOBKBf5ZZkU',
    appId: '1:598593524647:ios:6a158c37a8e71cdd7e1c82',
    messagingSenderId: '598593524647',
    projectId: 'urban-market-c3d86',
    storageBucket: 'urban-market-c3d86.firebasestorage.app',
    iosBundleId: 'com.example.urbanMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCupicvaRYmXfUkfugF74_Rai0VmyrhoOY',
    appId: '1:598593524647:web:8d09b536b76053c97e1c82',
    messagingSenderId: '598593524647',
    projectId: 'urban-market-c3d86',
    authDomain: 'urban-market-c3d86.firebaseapp.com',
    storageBucket: 'urban-market-c3d86.firebasestorage.app',
    measurementId: 'G-YM9QZP0NFX',
  );
}
